Migration table created successfully.
CreateUsersTable: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(60) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `lastname` varchar(255) not null, `pic_name` varchar(255) not null, `Resumes` varchar(255) not null, `telegram` varchar(255) not null, `field` varchar(255) not null, `phone` varchar(255) not null, `location` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp not null) default character set utf8 collate utf8_unicode_ci
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_token_index`(`token`)
CreateTasksTable: create table `tasks` (`id` int unsigned not null auto_increment primary key, `user_id` int not null, `name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci
CreateTasksTable: alter table `tasks` add index `tasks_user_id_index`(`user_id`)
CreateAcceptedsTable: create table `accepteds` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `work_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateAmbiguityUserWorkTable: create table `ambiguity_user_work` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `work_id` int not null, `ambiguity_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateAmbiguitysTable: create table `ambiguitys` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `name` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateApplicantsTable: create table `applicants` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `work_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateBranchFieldTable: create table `branch_field` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `branch_id` int not null, `field_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateBranchUserTable: create table `branch_user` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `branch_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateBranchsTable: create table `branchs` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `name` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateFieldUserTable: create table `field_user` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `field_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateFieldWorkTable: create table `field_work` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `field_id` int not null, `work_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateFieldsTable: create table `fields` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `name` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateOpinionUserWorkTable: create table `opinion_user_work` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `user_id` int not null, `work_id` int not null, `opinion_id` int not null) default character set utf8 collate utf8_unicode_ci
CreateOpinionsTable: create table `opinions` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `name` varchar(255) not null, `o1` varchar(255) not null, `o2` varchar(255) not null, `o3` varchar(255) not null, `o4` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateTagWorkTable: create table `tag_work` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `tag_id` int not null, `work_id` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateTagsTable: create table `tags` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `name` varchar(255) not null) default character set utf8 collate utf8_unicode_ci
CreateWorksTable: create table `works` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `subject` varchar(255) not null, `details` text not null, `deadtime` date not null, `filename` varchar(255) not null, `wage` int not null, `status` varchar(255) not null, `user_id` int unsigned not null) default character set utf8 collate utf8_unicode_ci
CreateForeignKeys: alter table `works` add constraint `works_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update restrict
